version: '3.7'
services:
  web:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      RACK_ENV: development
      DATABASE_URL: "postgres://postgres@db/production"
      DEVELOPMENT_DATABASE_URL: "postgres://postgres@db/development"
      TEST_DATABASE_URL: "postgres://postgres@db/test"
      REDIS_URL: "redis://redis:6379"
  db:
    image: postgres:10.3-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  redis:
    image: redis:alpine