development:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: portal-anime_development

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: portal-anime_production
